### ISSUE TITLE
'module 'deepchem.models' has no attribute 'TensorflowMultiTaskRegressor'

### ISSUE THREAD

**Issue by sandeepbii** [deepchem/deepchem#1315]
I have installed deepchem2.0.0 using conda install. I am tying to run the Solubility model from the deepchem tutorials. However I am getting the error
'module 'deepchem.models' has no attribute 'TensorflowMultiTaskRegressor'

I looked into the models directory and could not see the TensorflowMultiTaskRegressor model. I am not sure what to do. As I said I am quite new. Any help will be great.

Thanks
 Sandeep

**Comment by rbharath** [comment]
I think this example was broken previously. I'd recommend upgrading to HEAD. We've fixed all example recently so should run. (As a warning, HEAD may cause issues on Macs though)

**Comment by sandeepbii** [comment]
Thanks. I have installed deepchem from source as explained in the website. I still have the problem with TensorFlowMultiTaskRegressor. 

What does upgrading to HEAD mean? I am not sure if I understand that.

**Comment by peastman** [comment]
There's no such class as TensorFlowMultiTaskRegressor anymore.  In the current version of the source, it's been renamed to MultitaskRegressor.

**Comment by sandeepbii** [comment]
Thanks very much for your help.
