### ISSUE TITLE
sklearn.externals.joblib removed in 0.23

### ISSUE THREAD

**Issue by ulisrael** [deepchem/deepchem#1861]
**Description:**

If you installed by source please give us the git hash as well
>> git log | head -n 1
-->
- DeepChem Version: 2.3.0 
- Platform: py36_0 (python 3.6)

I think sklearn.externals.joblib has been removed and it is giving an error

~/anaconda3/envs/caltech_gnn/lib/python3.6/site-packages/deepchem/utils/save.py in <module>
      8 # TODO(rbharath): Use standard joblib once old-data has been regenerated.
      9 import joblib
---> 10 from sklearn.externals import joblib as old_joblib
     11 import gzip
     12 import json

ImportError: cannot import name 'joblib'

```
Your code sample here
```

**Comment by rbharath** [comment]
Good catch. It looks like the most recent sklearn release broke the deepchem 2.3.0 install. As a simple fix, can you try pinning sklearn=0.22.0 in your environment?

@peastman Should we perhaps do a release that fixes this error? We could do a 2.3.1 release that simply pins the sklearn version perhaps. As a second thought, perhaps we should also make a 2.4.0 cut quickly (and not wait for #1792 to be fully merged in). It's been 7 months since the last release already.

**Comment by peastman** [comment]
I think we could do 2.4 pretty soon.  Perhaps make up a list of what changes need to happen before releasing it?

**Comment by rbharath** [comment]
Ok, will do. It looks like TensorFlow 2.2.0 is out as well so we're clear on that end. I'll post an issue with a list of changes needed before the release.

**Comment by nd-02110114** [comment]
I think this error is too pain for many users , so I think we should release hotfix like this https://github.com/conda-forge/deepchem-feedstock/pull/2

**Comment by Laksh1997** [comment]
keen for this to be fixed, keep sklearn fixed at 0.22 until then!

**Comment by nd-02110114** [comment]
I think this issue is fixed, so retry installing the following command

```
pip install tensorflow==1.14 (or pip install tensorflow-gpu==1.14 )
conda install -c rdkit -c conda-forge rdkit deepchem==2.3.0
```

**Comment by nd-02110114** [comment]
I seem this issue was fixed

**Comment by Khalimat** [comment]
> Good catch. It looks like the most recent sklearn release broke the deepchem 2.3.0 install. As a simple fix, can you try pinning sklearn=0.22.0 in your environment?
> 
> @peastman Should we perhaps do a release that fixes this error? We could do a 2.3.1 release that simply pins the sklearn version perhaps. As a second thought, perhaps we should also make a 2.4.0 cut quickly (and not wait for #1792 to be fully merged in). It's been 7 months since the last release already.

Could you please inform, when I can expect the new release? I need scikit-learn>=0.23  (imbalanced-learn has such requirement) and deepchem in the same environment, but right now I still have problems with importing deepchem due to dependencies issues.

Thanks!

**Comment by rbharath** [comment]
@Khalimat Would it be feasible to use the nightly build for now? We're very close to the new release but have a couple of final tests to add in before we can make the cut. It'll probably be a week or two at the least. Sorry for the delay!
