### ISSUE TITLE
MolGraphConvFeaturizer.to_pyg_graph() contains multiple values for 'pos'

### ISSUE THREAD

**Issue by tonydavis629** [deepchem/deepchem#3142]
## 🐛 Bug

Loading a molnet dataset such as `dc.molnet.load_zinc15()` with the `MolGraphConvFeaturizer` fails when attempting to convert a sample into a pytorch geometric graph using `.to_pyg_graph()`. 

Each instance of the zinc15 dataset has an attribute `pos` which equals `array([], dtype=float64)` and `kwargs` which equals `{'pos':array([], dtype=float64)}`. Upon running `.to_pyg_graph()` on a sample, it seems these two values clash in the torch_geometric.data.Data constructor. I have also tested this with qm9 with the same results.

## To Reproduce

```
import deepchem as dc
from deepchem.feat.molecule_featurizers import MolGraphConvFeaturizer

featurizer = MolGraphConvFeaturizer(use_edges=True)
dataset_dc = dc.molnet.load_zinc15(featurizer=featurizer)
tasks, dataset, transformers = dataset_dc
train, valid, test = dataset

x,y,w,ids = train.X, train.y, train.w, train.ids

example = x[0].to_pyg_graph()
```

Exception has occurred: TypeError
torch_geometric.data.data.Data() got multiple values for keyword argument 'pos'

## Expected behavior

The sample should be able to be converted into a pytorch geometric graph object.

## Environment

* OS: Ubuntu 22.04
* Python version: 3.9.15
* DeepChem version: 2.7.1
* RDKit version (optional):
* TensorFlow version (optional):
* PyTorch version (optional):
* Any other relevant information:

**Comment by arunppsg** [comment]
This is similar to #3090. There is an open PR #3097. Will post updates on this by today.

**Comment by gusty1g** [comment]
Fixed in #3097

**Comment by sk000007** [comment]
This bug still seems to exist...ver 2.7.1..installed with pip.
